@ECHO OFF
REM *** WINDOWS DEPLOYMENT AUTOMATION (WinDA) Tool Documentation***
ECHO === WinDA Instructions ===
ECHO PRESS 'ENTER' AT EVERY PROMPT TO READ FURTHER!
TIMEOUT /T 2 /NOBREAK >NUL
SET /P INSTRUCT="- THIS SCRIPT IS CURRENTLY A WORK-IN-PROGRESS"
SET /P INSTRUCT="- CERTAIN FUNCTIONALITY & FEATURES MAY BE LACKING"
SET /P INSTRUCT="- AT THIS POINT OF DEVELOPMENT, WINDA UTILIZES ROBOCOPY TO MIGRATE DESKTOP, DOWNLOADS, DOCUMENTS, PICTURES, AND  DEFAULT  PROFILE BOOKMARKS (MIGRATING EXTRA PROFILE BOOKMARKS IS A FEATURE CURRENTLY BEING IMPLEMENTED)"
SET /P INSTRUCT="- ALWAYS RUN THIS SCRIPT ON THE OLD WORKSTATION!!!"
SET /P INSTRUCT="1. Run the script as a NETWORK Administrator (REQUIRED TO CONNECT TO COMPUTERS OVER THE NETWORK, ***LOCAL ADMIN WILL NOT WORK***)"
SET /P INSTRUCT="2. The first prompt will require the user's RACFID, please double check the RACFID with the user to avoid the script creating another target directory in the C:/Users directory!"
SET /P INSTRUCT="3. The second prompt will require the IP address of the ***NEW*** asset, please double check the IP address or ROBOCOPY WILL fail!!!"
SET /P INSTRUCT="- ROBOCOPY WILL RUN AT THIS POINT USING THE VARIABLES PROVIDED BY THE SCRIPT USER"
SET /P INSTRUCT="- A popup will appear for a brief moment explicitly stating that data migration has been completed"
PAUSE